version: '3.8'

services:
  app:
    build: .
    container_name: shopper_app
    command: npm run dev
    restart: always
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - db_data:/usr/src/app/db
    ports:
      - 3001:3001
    env_file:
      - .env

volumes:
  db_data:
